
/*
  Generated by Polychrony version  V4.19
*/
#include "abs_types.h"
#include "abs_externals.h"
#include "abs_body.h"

/*  ==> parameters and indexes */
/*  ==> input signals     */
static int i;
/*  ==> output signals    */
static int o;
/*  ==> local signals     */

EXTERN boolean abs_initialize()
{
    abs_step_initialize();
    return TRUE;
}

static void abs_step_initialize()
{
}

EXTERN boolean abs_step()
{
    if (!r_abs_i(&i)) return FALSE;
    if (i > 0) o = i; else o = -i; 
    w_abs_o(o);
    abs_step_finalize();
    return TRUE;
}

EXTERN boolean abs_step_finalize()
{
    abs_step_initialize();
    return TRUE;
}

