
/*
  Generated by Polychrony version  V4.19
*/
#include "abs_types.h"
#include "abs_externals.h"
static FILE
    *fri,
    *fwo;

/*----The following line must be uncommented for the VCD mode*/
/*#define _DUMPFILE_VCD_*/

#ifdef _DUMPFILE_VCD_
#include "pK_vcd.h"
#define _VCD_STEP_ 1
#endif

EXTERN void abs_OpenIO()
{
    #ifdef _DUMPFILE_VCD_
    fw_DUMPFILE_VCD_ = fopen("W_DUMPFILE_VCD_.dat","w");
    if (!fw_DUMPFILE_VCD_)
        {
        fprintf(stderr,"Can not open file %s\n","W_DUMPFILE_VCD_.dat");
        exit(1);
        }
    
    fprintf(fw_DUMPFILE_VCD_,"$version\n");
    fprintf(fw_DUMPFILE_VCD_,"  Generated by Polychrony version   ");
    fprintf(fw_DUMPFILE_VCD_,"V4.19\n");
    fprintf(fw_DUMPFILE_VCD_,"$end\n");
    fprintf(fw_DUMPFILE_VCD_,"$timescale\n");
    fprintf(fw_DUMPFILE_VCD_,"    1 ns\n");
    fprintf(fw_DUMPFILE_VCD_,"$end\n");
    #endif
    fri = fopen("Ri.dat","r");
    if (!fri)
        {
        fprintf(stderr,"Can not open file %s\n","Ri.dat");
        exit(1);
        }
    
    #ifdef _DUMPFILE_VCD_
    fprintf(fw_DUMPFILE_VCD_,"$var ");
    fprintf(fw_DUMPFILE_VCD_,"integer ");
    fprintf(fw_DUMPFILE_VCD_,"32 ");
    fprintf(fw_DUMPFILE_VCD_,"<_1 ");
    fprintf(fw_DUMPFILE_VCD_,"i ");
    fprintf(fw_DUMPFILE_VCD_,"$end\n");
    #endif
    fwo = fopen("Wo.dat","w");
    if (!fwo)
        {
        fprintf(stderr,"Can not open file %s\n","Wo.dat");
        exit(1);
        }
    
    #ifdef _DUMPFILE_VCD_
    fprintf(fw_DUMPFILE_VCD_,"$var ");
    fprintf(fw_DUMPFILE_VCD_,"integer ");
    fprintf(fw_DUMPFILE_VCD_,"32 ");
    fprintf(fw_DUMPFILE_VCD_,"<_2 ");
    fprintf(fw_DUMPFILE_VCD_,"o ");
    fprintf(fw_DUMPFILE_VCD_,"$end\n");
    #endif
    #ifdef _DUMPFILE_VCD_
    fprintf(fw_DUMPFILE_VCD_,"$enddefinitions ");
    fprintf(fw_DUMPFILE_VCD_,"$end\n");
    #endif
}

EXTERN void abs_CloseIO()
{
    fclose(fri);
    fclose(fwo);
    #ifdef _DUMPFILE_VCD_
    fclose(fw_DUMPFILE_VCD_);
    #endif
}

EXTERN boolean r_abs_i(int *i)
{
    if (fscanf(fri,"%d",i)==EOF)return FALSE;
    #ifdef _DUMPFILE_VCD_
    print_VCD_int(*i);
    fprintf(fw_DUMPFILE_VCD_,"<_1\n");
    #endif
    return TRUE;
}

EXTERN void w_abs_o(int o)
{
    fprintf(fwo,"%d ",o);
    #ifdef _DUMPFILE_VCD_
    print_VCD_int(o);
    fprintf(fw_DUMPFILE_VCD_,"<_2\n");
    #endif
    fprintf(fwo,"\n");
    fflush(fwo);
}

EXTERN void abs_stepIO_begin()
{
    #ifdef _DUMPFILE_VCD_
    fprintf(fw_DUMPFILE_VCD_,"#%d\n",_vcd_counter_);
    _vcd_counter_ = _vcd_counter_ + _VCD_STEP_;
    fflush(fw_DUMPFILE_VCD_);
    _VCD_setStep();
    #endif
}

EXTERN void abs_stepIO_end()
{
}

