
/*
  Generated by Polychrony version  V4.19
*/
#include "abs_types.h"
#include "abs_externals.h"
#include "abs_body.h"
EXTERN void abs_OpenIO();
EXTERN void abs_CloseIO();
EXTERN void abs_stepIO_begin();
EXTERN void abs_stepIO_end();

EXTERN int main()
{
    boolean code;
    abs_OpenIO();
    code = abs_initialize();
    while(code)
      {
        abs_stepIO_begin();
        code = abs_step();
        abs_stepIO_end();
    }
    abs_CloseIO();
}

