
/*
  Generated by Polychrony version  V4.19
*/
#include "identite_types.h"
#include "identite_externals.h"
#include "identite_body.h"

/*  ==> parameters and indexes */
/*  ==> input signals     */
static float e;
/*  ==> output signals    */
static float s;
/*  ==> local signals     */

EXTERN boolean identite_initialize()
{
    identite_step_initialize();
    return TRUE;
}

static void identite_step_initialize()
{
}

EXTERN boolean identite_step()
{
    if (!r_identite_e(&e)) return FALSE;
    s = 0.5 * (2.0 * e);
    w_identite_s(s);
    identite_step_finalize();
    return TRUE;
}

EXTERN boolean identite_step_finalize()
{
    identite_step_initialize();
    return TRUE;
}

