
/*
  Generated by Polychrony version  V4.19
*/
#include "identite_types.h"
#include "identite_externals.h"
#include "identite_body.h"
EXTERN void identite_OpenIO();
EXTERN void identite_CloseIO();
EXTERN void identite_stepIO_begin();
EXTERN void identite_stepIO_end();

EXTERN int main()
{
    boolean code;
    identite_OpenIO();
    code = identite_initialize();
    while(code)
      {
        identite_stepIO_begin();
        code = identite_step();
        identite_stepIO_end();
    }
    identite_CloseIO();
}

