
/*
  Generated by Polychrony version  V4.19
*/
#include "bistable_types.h"
#include "bistable_externals.h"
#include "bistable_body.h"

/*  ==> parameters and indexes */
/*  ==> input signals     */
static boolean top;
/*  ==> output signals    */
static boolean sortie, fdp;
/*  ==> local signals     */
static boolean zsortie, C_CLK_12, C_CLK_26, C_fdp;

EXTERN boolean bistable_initialize()
{
    zsortie = FALSE;
    bistable_step_initialize();
    return TRUE;
}

static void bistable_step_initialize()
{
}

EXTERN boolean bistable_step()
{
    if (!r_bistable_top(&top)) return FALSE;
    if (top)
        {
        sortie = !zsortie;
        w_bistable_sortie(sortie);
        C_CLK_12 = !zsortie;
        C_CLK_26 = zsortie && !sortie;
        C_fdp = C_CLK_26 || C_CLK_12;
        if (C_fdp)
            {
            if (C_CLK_26) fdp = TRUE; else fdp = sortie; 
            w_bistable_fdp(fdp);
            }
        }
    bistable_step_finalize();
    return TRUE;
}

EXTERN boolean bistable_step_finalize()
{
    if (top)
        {
        zsortie = sortie;
        }
    bistable_step_initialize();
    return TRUE;
}

