
/*
  Generated by Polychrony version  V4.19
*/
#include "bistable_types.h"
#include "bistable_externals.h"
static FILE
    *frtop,
    *fwsortie,
    *fwfdp;

/*----The following line must be uncommented for the VCD mode*/
/*#define _DUMPFILE_VCD_*/

#ifdef _DUMPFILE_VCD_
#include "pK_vcd.h"
#define _VCD_STEP_ 1
#endif

EXTERN void bistable_OpenIO()
{
    #ifdef _DUMPFILE_VCD_
    fw_DUMPFILE_VCD_ = fopen("W_DUMPFILE_VCD_.dat","w");
    if (!fw_DUMPFILE_VCD_)
        {
        fprintf(stderr,"Can not open file %s\n","W_DUMPFILE_VCD_.dat");
        exit(1);
        }
    
    fprintf(fw_DUMPFILE_VCD_,"$version\n");
    fprintf(fw_DUMPFILE_VCD_,"  Generated by Polychrony version   ");
    fprintf(fw_DUMPFILE_VCD_,"V4.19\n");
    fprintf(fw_DUMPFILE_VCD_,"$end\n");
    fprintf(fw_DUMPFILE_VCD_,"$timescale\n");
    fprintf(fw_DUMPFILE_VCD_,"    1 ns\n");
    fprintf(fw_DUMPFILE_VCD_,"$end\n");
    #endif
    frtop = fopen("Rtop.dat","r");
    if (!frtop)
        {
        fprintf(stderr,"Can not open file %s\n","Rtop.dat");
        exit(1);
        }
    
    #ifdef _DUMPFILE_VCD_
    fprintf(fw_DUMPFILE_VCD_,"$var ");
    fprintf(fw_DUMPFILE_VCD_,"trireg ");
    fprintf(fw_DUMPFILE_VCD_,"1 ");
    fprintf(fw_DUMPFILE_VCD_,"<_1 ");
    fprintf(fw_DUMPFILE_VCD_,"top ");
    fprintf(fw_DUMPFILE_VCD_,"$end\n");
    #endif
    fwsortie = fopen("Wsortie.dat","w");
    if (!fwsortie)
        {
        fprintf(stderr,"Can not open file %s\n","Wsortie.dat");
        exit(1);
        }
    
    #ifdef _DUMPFILE_VCD_
    fprintf(fw_DUMPFILE_VCD_,"$var ");
    fprintf(fw_DUMPFILE_VCD_,"trireg ");
    fprintf(fw_DUMPFILE_VCD_,"1 ");
    fprintf(fw_DUMPFILE_VCD_,"<_2 ");
    fprintf(fw_DUMPFILE_VCD_,"sortie ");
    fprintf(fw_DUMPFILE_VCD_,"$end\n");
    #endif
    fwfdp = fopen("Wfdp.dat","w");
    if (!fwfdp)
        {
        fprintf(stderr,"Can not open file %s\n","Wfdp.dat");
        exit(1);
        }
    
    #ifdef _DUMPFILE_VCD_
    fprintf(fw_DUMPFILE_VCD_,"$var ");
    fprintf(fw_DUMPFILE_VCD_,"trireg ");
    fprintf(fw_DUMPFILE_VCD_,"1 ");
    fprintf(fw_DUMPFILE_VCD_,"<_3 ");
    fprintf(fw_DUMPFILE_VCD_,"fdp ");
    fprintf(fw_DUMPFILE_VCD_,"$end\n");
    #endif
    #ifdef _DUMPFILE_VCD_
    fprintf(fw_DUMPFILE_VCD_,"$enddefinitions ");
    fprintf(fw_DUMPFILE_VCD_,"$end\n");
    #endif
}

EXTERN void bistable_CloseIO()
{
    fclose(frtop);
    fclose(fwsortie);
    fclose(fwfdp);
    #ifdef _DUMPFILE_VCD_
    fclose(fw_DUMPFILE_VCD_);
    #endif
}

EXTERN boolean r_bistable_top(boolean *top)
{
    if (fscanf(frtop,"%d",top)==EOF)return FALSE;
    #ifdef _DUMPFILE_VCD_
    print_VCD_boolean(*top);
    fprintf(fw_DUMPFILE_VCD_,"<_1\n");
    #endif
    return TRUE;
}

EXTERN void w_bistable_sortie(boolean sortie)
{
    fprintf(fwsortie,"%d ",sortie);
    #ifdef _DUMPFILE_VCD_
    print_VCD_boolean(sortie);
    fprintf(fw_DUMPFILE_VCD_,"<_2\n");
    #endif
    fprintf(fwsortie,"\n");
    fflush(fwsortie);
}

EXTERN void w_bistable_fdp(boolean fdp)
{
    fprintf(fwfdp,"%d ",fdp);
    #ifdef _DUMPFILE_VCD_
    print_VCD_boolean(fdp);
    fprintf(fw_DUMPFILE_VCD_,"<_3\n");
    #endif
    fprintf(fwfdp,"\n");
    fflush(fwfdp);
}

EXTERN void bistable_stepIO_begin()
{
    #ifdef _DUMPFILE_VCD_
    fprintf(fw_DUMPFILE_VCD_,"#%d\n",_vcd_counter_);
    _vcd_counter_ = _vcd_counter_ + _VCD_STEP_;
    fflush(fw_DUMPFILE_VCD_);
    _VCD_setStep();
    #endif
}

EXTERN void bistable_stepIO_end()
{
}

