
/*
  Generated by Polychrony version  V4.19
*/
#include "cptmodO_types.h"
#include "cptmodO_externals.h"
#include "cptmodO_body.h"
EXTERN void cptmodO_OpenIO();
EXTERN void cptmodO_CloseIO();
EXTERN void cptmodO_stepIO_begin();
EXTERN void cptmodO_stepIO_end();

EXTERN int main()
{
    boolean code;
    cptmodO_OpenIO();
    code = cptmodO_initialize();
    while(code)
      {
        cptmodO_stepIO_begin();
        code = cptmodO_step();
        cptmodO_stepIO_end();
    }
    cptmodO_CloseIO();
}

