
/*
  Generated by Polychrony version  V4.19
*/
#include "cptmodO_types.h"
#include "cptmodO_externals.h"
#include "cptmodO_body.h"

/*  ==> parameters and indexes */
/*  ==> input signals     */
static boolean top;
/*  ==> output signals    */
static int n;
/*  ==> local signals     */
static boolean C_CLK;

EXTERN boolean cptmodO_initialize()
{
    n = 0;
    cptmodO_step_initialize();
    return TRUE;
}

static void cptmodO_step_initialize()
{
}

EXTERN boolean cptmodO_step()
{
    if (!r_cptmodO_top(&top)) return FALSE;
    C_CLK = n >= 5;
    if (C_CLK) n = 1; else n = n + 1; 
    w_cptmodO_n(n);
    cptmodO_step_finalize();
    return TRUE;
}

EXTERN boolean cptmodO_step_finalize()
{
    cptmodO_step_initialize();
    return TRUE;
}

