
/*
  Generated by Polychrony version  V4.19
*/
#include "cptmodO_types.h"
#include "cptmodO_externals.h"
static FILE
    *frtop,
    *fwn;

/*----The following line must be uncommented for the VCD mode*/
/*#define _DUMPFILE_VCD_*/

#ifdef _DUMPFILE_VCD_
#include "pK_vcd.h"
#define _VCD_STEP_ 1
#endif

EXTERN void cptmodO_OpenIO()
{
    #ifdef _DUMPFILE_VCD_
    fw_DUMPFILE_VCD_ = fopen("W_DUMPFILE_VCD_.dat","w");
    if (!fw_DUMPFILE_VCD_)
        {
        fprintf(stderr,"Can not open file %s\n","W_DUMPFILE_VCD_.dat");
        exit(1);
        }
    
    fprintf(fw_DUMPFILE_VCD_,"$version\n");
    fprintf(fw_DUMPFILE_VCD_,"  Generated by Polychrony version   ");
    fprintf(fw_DUMPFILE_VCD_,"V4.19\n");
    fprintf(fw_DUMPFILE_VCD_,"$end\n");
    fprintf(fw_DUMPFILE_VCD_,"$timescale\n");
    fprintf(fw_DUMPFILE_VCD_,"    1 ns\n");
    fprintf(fw_DUMPFILE_VCD_,"$end\n");
    #endif
    frtop = fopen("Rtop.dat","r");
    if (!frtop)
        {
        fprintf(stderr,"Can not open file %s\n","Rtop.dat");
        exit(1);
        }
    
    #ifdef _DUMPFILE_VCD_
    fprintf(fw_DUMPFILE_VCD_,"$var ");
    fprintf(fw_DUMPFILE_VCD_,"trireg ");
    fprintf(fw_DUMPFILE_VCD_,"1 ");
    fprintf(fw_DUMPFILE_VCD_,"<_1 ");
    fprintf(fw_DUMPFILE_VCD_,"top ");
    fprintf(fw_DUMPFILE_VCD_,"$end\n");
    #endif
    fwn = fopen("Wn.dat","w");
    if (!fwn)
        {
        fprintf(stderr,"Can not open file %s\n","Wn.dat");
        exit(1);
        }
    
    #ifdef _DUMPFILE_VCD_
    fprintf(fw_DUMPFILE_VCD_,"$var ");
    fprintf(fw_DUMPFILE_VCD_,"integer ");
    fprintf(fw_DUMPFILE_VCD_,"32 ");
    fprintf(fw_DUMPFILE_VCD_,"<_2 ");
    fprintf(fw_DUMPFILE_VCD_,"n ");
    fprintf(fw_DUMPFILE_VCD_,"$end\n");
    #endif
    #ifdef _DUMPFILE_VCD_
    fprintf(fw_DUMPFILE_VCD_,"$enddefinitions ");
    fprintf(fw_DUMPFILE_VCD_,"$end\n");
    #endif
}

EXTERN void cptmodO_CloseIO()
{
    fclose(frtop);
    fclose(fwn);
    #ifdef _DUMPFILE_VCD_
    fclose(fw_DUMPFILE_VCD_);
    #endif
}

EXTERN boolean r_cptmodO_top(boolean *top)
{
    if (fscanf(frtop,"%d",top)==EOF)return FALSE;
    #ifdef _DUMPFILE_VCD_
    print_VCD_boolean(*top);
    fprintf(fw_DUMPFILE_VCD_,"<_1\n");
    #endif
    return TRUE;
}

EXTERN void w_cptmodO_n(int n)
{
    fprintf(fwn,"%d ",n);
    #ifdef _DUMPFILE_VCD_
    print_VCD_int(n);
    fprintf(fw_DUMPFILE_VCD_,"<_2\n");
    #endif
    fprintf(fwn,"\n");
    fflush(fwn);
}

EXTERN void cptmodO_stepIO_begin()
{
    #ifdef _DUMPFILE_VCD_
    fprintf(fw_DUMPFILE_VCD_,"#%d\n",_vcd_counter_);
    _vcd_counter_ = _vcd_counter_ + _VCD_STEP_;
    fflush(fw_DUMPFILE_VCD_);
    _VCD_setStep();
    #endif
}

EXTERN void cptmodO_stepIO_end()
{
}

