
/*
  Generated by Polychrony version  V4.19
*/
#include "polcar_types.h"
#include "polcar_externals.h"
#include "polcar_body.h"

/*  ==> parameters and indexes */
/*  ==> input signals     */
static double r, a;
/*  ==> output signals    */
static double x, y;
/*  ==> local signals     */

EXTERN boolean polcar_initialize()
{
    polcar_step_initialize();
    return TRUE;
}

static void polcar_step_initialize()
{
}

EXTERN boolean polcar_step()
{
    if (!r_polcar_r(&r)) return FALSE;
    if (!r_polcar_a(&a)) return FALSE;
    x = r * cos(a);
    y = r * sin(a);
    w_polcar_x(x);
    w_polcar_y(y);
    polcar_step_finalize();
    return TRUE;
}

EXTERN boolean polcar_step_finalize()
{
    polcar_step_initialize();
    return TRUE;
}

