
/*
  Generated by Polychrony version  V4.19
*/
#include "polcar_types.h"
#include "polcar_externals.h"
static FILE
    *frr,
    *fra,
    *fwx,
    *fwy;

/*----The following line must be uncommented for the VCD mode*/
/*#define _DUMPFILE_VCD_*/

#ifdef _DUMPFILE_VCD_
#include "pK_vcd.h"
#define _VCD_STEP_ 1
#endif

EXTERN void polcar_OpenIO()
{
    #ifdef _DUMPFILE_VCD_
    fw_DUMPFILE_VCD_ = fopen("W_DUMPFILE_VCD_.dat","w");
    if (!fw_DUMPFILE_VCD_)
        {
        fprintf(stderr,"Can not open file %s\n","W_DUMPFILE_VCD_.dat");
        exit(1);
        }
    
    fprintf(fw_DUMPFILE_VCD_,"$version\n");
    fprintf(fw_DUMPFILE_VCD_,"  Generated by Polychrony version   ");
    fprintf(fw_DUMPFILE_VCD_,"V4.19\n");
    fprintf(fw_DUMPFILE_VCD_,"$end\n");
    fprintf(fw_DUMPFILE_VCD_,"$timescale\n");
    fprintf(fw_DUMPFILE_VCD_,"    1 ns\n");
    fprintf(fw_DUMPFILE_VCD_,"$end\n");
    #endif
    frr = fopen("Rr.dat","r");
    if (!frr)
        {
        fprintf(stderr,"Can not open file %s\n","Rr.dat");
        exit(1);
        }
    
    #ifdef _DUMPFILE_VCD_
    fprintf(fw_DUMPFILE_VCD_,"$var ");
    fprintf(fw_DUMPFILE_VCD_,"real ");
    fprintf(fw_DUMPFILE_VCD_,"32 ");
    fprintf(fw_DUMPFILE_VCD_,"<_1 ");
    fprintf(fw_DUMPFILE_VCD_,"r ");
    fprintf(fw_DUMPFILE_VCD_,"$end\n");
    #endif
    fra = fopen("Ra.dat","r");
    if (!fra)
        {
        fprintf(stderr,"Can not open file %s\n","Ra.dat");
        exit(1);
        }
    
    #ifdef _DUMPFILE_VCD_
    fprintf(fw_DUMPFILE_VCD_,"$var ");
    fprintf(fw_DUMPFILE_VCD_,"real ");
    fprintf(fw_DUMPFILE_VCD_,"32 ");
    fprintf(fw_DUMPFILE_VCD_,"<_2 ");
    fprintf(fw_DUMPFILE_VCD_,"a ");
    fprintf(fw_DUMPFILE_VCD_,"$end\n");
    #endif
    fwx = fopen("Wx.dat","w");
    if (!fwx)
        {
        fprintf(stderr,"Can not open file %s\n","Wx.dat");
        exit(1);
        }
    
    #ifdef _DUMPFILE_VCD_
    fprintf(fw_DUMPFILE_VCD_,"$var ");
    fprintf(fw_DUMPFILE_VCD_,"real ");
    fprintf(fw_DUMPFILE_VCD_,"32 ");
    fprintf(fw_DUMPFILE_VCD_,"<_3 ");
    fprintf(fw_DUMPFILE_VCD_,"x ");
    fprintf(fw_DUMPFILE_VCD_,"$end\n");
    #endif
    fwy = fopen("Wy.dat","w");
    if (!fwy)
        {
        fprintf(stderr,"Can not open file %s\n","Wy.dat");
        exit(1);
        }
    
    #ifdef _DUMPFILE_VCD_
    fprintf(fw_DUMPFILE_VCD_,"$var ");
    fprintf(fw_DUMPFILE_VCD_,"real ");
    fprintf(fw_DUMPFILE_VCD_,"32 ");
    fprintf(fw_DUMPFILE_VCD_,"<_4 ");
    fprintf(fw_DUMPFILE_VCD_,"y ");
    fprintf(fw_DUMPFILE_VCD_,"$end\n");
    #endif
    #ifdef _DUMPFILE_VCD_
    fprintf(fw_DUMPFILE_VCD_,"$enddefinitions ");
    fprintf(fw_DUMPFILE_VCD_,"$end\n");
    #endif
}

EXTERN void polcar_CloseIO()
{
    fclose(frr);
    fclose(fra);
    fclose(fwx);
    fclose(fwy);
    #ifdef _DUMPFILE_VCD_
    fclose(fw_DUMPFILE_VCD_);
    #endif
}

EXTERN boolean r_polcar_r(double *r)
{
    if (fscanf(frr,"%lf",r)==EOF)return FALSE;
    #ifdef _DUMPFILE_VCD_
    print_VCD_double(*r);
    fprintf(fw_DUMPFILE_VCD_,"<_1\n");
    #endif
    return TRUE;
}

EXTERN boolean r_polcar_a(double *a)
{
    if (fscanf(fra,"%lf",a)==EOF)return FALSE;
    #ifdef _DUMPFILE_VCD_
    print_VCD_double(*a);
    fprintf(fw_DUMPFILE_VCD_,"<_2\n");
    #endif
    return TRUE;
}

EXTERN void w_polcar_x(double x)
{
    fprintf(fwx,"%lf ",x);
    #ifdef _DUMPFILE_VCD_
    print_VCD_double(x);
    fprintf(fw_DUMPFILE_VCD_,"<_3\n");
    #endif
    fprintf(fwx,"\n");
    fflush(fwx);
}

EXTERN void w_polcar_y(double y)
{
    fprintf(fwy,"%lf ",y);
    #ifdef _DUMPFILE_VCD_
    print_VCD_double(y);
    fprintf(fw_DUMPFILE_VCD_,"<_4\n");
    #endif
    fprintf(fwy,"\n");
    fflush(fwy);
}

EXTERN void polcar_stepIO_begin()
{
    #ifdef _DUMPFILE_VCD_
    fprintf(fw_DUMPFILE_VCD_,"#%d\n",_vcd_counter_);
    _vcd_counter_ = _vcd_counter_ + _VCD_STEP_;
    fflush(fw_DUMPFILE_VCD_);
    _VCD_setStep();
    #endif
}

EXTERN void polcar_stepIO_end()
{
}

