
/*
  Generated by Polychrony version  V4.19
*/
#include "cptmod_types.h"
#include "cptmod_externals.h"
#include "cptmod_body.h"

/*  ==> parameters and indexes */
/*  ==> input signals     */
static boolean top;
/*  ==> output signals    */
static int n;
/*  ==> local signals     */
static int temp;

EXTERN boolean cptmod_initialize()
{
    temp = 0;
    cptmod_step_initialize();
    return TRUE;
}

static void cptmod_step_initialize()
{
}

EXTERN boolean cptmod_step()
{
    if (!r_cptmod_top(&top)) return FALSE;
    temp = temp + 1;
    if (temp > M) n = 0; else n = temp; 
    w_cptmod_n(n);
    cptmod_step_finalize();
    return TRUE;
}

EXTERN boolean cptmod_step_finalize()
{
    cptmod_step_initialize();
    return TRUE;
}

