
/*
  Generated by Polychrony version  V4.19
*/
#include "mul2_types.h"
#include "mul2_externals.h"
#include "mul2_body.h"
EXTERN void mul2_OpenIO();
EXTERN void mul2_CloseIO();
EXTERN void mul2_stepIO_begin();
EXTERN void mul2_stepIO_end();

EXTERN int main()
{
    boolean code;
    mul2_OpenIO();
    code = mul2_initialize();
    while(code)
      {
        mul2_stepIO_begin();
        code = mul2_step();
        mul2_stepIO_end();
    }
    mul2_CloseIO();
}

